# Generated by Django 5.2.6 on 2025-09-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='interface_sorting',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
